#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import urllib.parse

def abort_with_help():
    print("Usage: %s <e|ex|d|dx>" % os.path.basename(sys.argv[0]))
    exit(1)

if (len(sys.argv) != 2):
    abort_with_help()

mode = sys.argv[1]
if (mode not in ['e', 'd']):
    abort_with_help()

for line in sys.stdin:
    text = line.rstrip()
    if mode == 'e':
        print(urllib.parse.quote(text))
    elif mode == 'd':
        print(urllib.parse.unquote(text))
