#!/usr/bin/env bash

usage () {
  echo "Usage: $( basename $0 ) <e|d>"
}

if [ "$#" -ne 1 ]; then
  usage
  exit 1
fi

if [ "$1" = "e" ]; then
  cat - | ruby -ruri -ne 'print URI.encode($_, " \"$&+,/:;=?@[]<>|")'
elif [ "$1" = "d" ]; then
  cat - | ruby -ruri -ne 'print URI.decode($_)'
else
  usage
  exit 1
fi
